services:
    telegram-proxy:
        image: telegrammessenger/proxy:latest
        container_name: tg-proxy
        expose:
          - "8443:8443"
        volumes:
           - "proxy-config:/data"
        restart: unless-stopped
        environment: 
            TAG: "${PROXY_TAG}"
            SECRET: "${PROXY_SECRET}"
            SECRET_COUNT: "${PROXY_SECRET_COUNT:-4}"
            WORKERS: "${PROXY_WORKERS:-16}"

    tg-proxy-watchtower:
        image: v2tec/watchtower
        container_name: tg-proxy-watchtower
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /root/.docker/config.json:/config.json
        command: telegrammessenger/proxy:latest
        restart: unless-stopped
        
    cloudflared:
        container_name: cloudflared
        image: erisamoe/cloudflared:latest
        restart: unless-stopped
        command: 'tunnel run'
        environment:
          TUNNEL_TOKEN: "${CLOUDFLARED_TOKEN}"
        depends_on:
          - telegram-proxy:
          - tg-proxy-watchtower
volumes:
  proxy-config:
